# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Concept(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, score=None, type=None):  # noqa: E501
        """Concept - a model defined in OpenAPI

        :param name: The name of this Concept.  # noqa: E501
        :type name: str
        :param score: The score of this Concept.  # noqa: E501
        :type score: float
        :param type: The type of this Concept.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'name': str,
            'score': float,
            'type': str
        }

        self.attribute_map = {
            'name': 'name',
            'score': 'score',
            'type': 'type'
        }

        self._name = name
        self._score = score
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Concept':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Concept of this Concept.  # noqa: E501
        :rtype: Concept
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Concept.

        The object name  # noqa: E501

        :return: The name of this Concept.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Concept.

        The object name  # noqa: E501

        :param name: The name of this Concept.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def score(self):
        """Gets the score of this Concept.

        The score for the object in relation to the concept (higher is closer match)  # noqa: E501

        :return: The score of this Concept.
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this Concept.

        The score for the object in relation to the concept (higher is closer match)  # noqa: E501

        :param score: The score of this Concept.
        :type score: float
        """
        if score is None:
            raise ValueError("Invalid value for `score`, must not be `None`")  # noqa: E501

        self._score = score

    @property
    def type(self):
        """Gets the type of this Concept.

        Whether the object is related to a model, parameter, or output  # noqa: E501

        :return: The type of this Concept.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Concept.

        Whether the object is related to a model, parameter, or output  # noqa: E501

        :param type: The type of this Concept.
        :type type: str
        """
        allowed_values = ["model", "output", "parameter"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
