# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ModelConfig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, config=None, valid=None, error=None):  # noqa: E501
        """ModelConfig - a model defined in OpenAPI

        :param name: The name of this ModelConfig.  # noqa: E501
        :type name: str
        :param config: The config of this ModelConfig.  # noqa: E501
        :type config: object
        :param valid: The valid of this ModelConfig.  # noqa: E501
        :type valid: bool
        :param error: The error of this ModelConfig.  # noqa: E501
        :type error: str
        """
        self.openapi_types = {
            'name': str,
            'config': object,
            'valid': bool,
            'error': str
        }

        self.attribute_map = {
            'name': 'name',
            'config': 'config',
            'valid': 'valid',
            'error': 'error'
        }

        self._name = name
        self._config = config
        self._valid = valid
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'ModelConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelConfig of this ModelConfig.  # noqa: E501
        :rtype: ModelConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ModelConfig.

        A model's name  # noqa: E501

        :return: The name of this ModelConfig.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelConfig.

        A model's name  # noqa: E501

        :param name: The name of this ModelConfig.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def config(self):
        """Gets the config of this ModelConfig.


        :return: The config of this ModelConfig.
        :rtype: object
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this ModelConfig.


        :param config: The config of this ModelConfig.
        :type config: object
        """
        if config is None:
            raise ValueError("Invalid value for `config`, must not be `None`")  # noqa: E501

        self._config = config

    @property
    def valid(self):
        """Gets the valid of this ModelConfig.


        :return: The valid of this ModelConfig.
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this ModelConfig.


        :param valid: The valid of this ModelConfig.
        :type valid: bool
        """

        self._valid = valid

    @property
    def error(self):
        """Gets the error of this ModelConfig.


        :return: The error of this ModelConfig.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ModelConfig.


        :param error: The error of this ModelConfig.
        :type error: str
        """

        self._error = error
