ALTER TABLE metadata ADD created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE metadata ADD updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE parameters ADD created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE parameters ADD updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE output ADD created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE output ADD updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

CREATE OR REPLACE FUNCTION updated()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = now();
	RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER metadata_updated BEFORE
UPDATE ON metadata
FOR EACH ROW EXECUTE PROCEDURE updated();

CREATE TRIGGER parameters_updated BEFORE
UPDATE ON parameters
FOR EACH ROW EXECUTE PROCEDURE updated();

CREATE TRIGGER output_updated BEFORE
UPDATE ON output
FOR EACH ROW EXECUTE PROCEDURE updated();